services:
  todo-app-backend:
    image: node:18-alpine
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./server:/app
    command: sh -c "npm start"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  
  todo-app:
    image: node:18-alpine
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm start"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
  
  mysql:
    image: mysql:8.0
    volumes:
      - todo-app-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-app-data: