version: "v1.0"
services:
  mysql:
    image: mysql:8.0
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

  todo-app-dnd-server:
    image: oos1111/todo-app-dnd-server:1.0
    ports:
      - 3001:3001
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  
  todo-app-dnd-client:
    image: oos1111/todo-app-dnd-client:1.0
    ports:
      - 3000:3000
  


volumes:
  data: